import { StyleSheet } from "react-native";

export const Colors = {
  background: "#f5f6ff",
  foreground: "#0d0f2b",
  card: "#ffffff",
  cardForeground: "#0d0f2b",
  primary: "#5046e5",
  primaryLight: "#ebe9fd",
  primaryGlow: "#7c70f0",
  primaryForeground: "#ffffff",
  secondary: "#f0f0fe",
  secondaryForeground: "#1e1b4b",
  muted: "#f8f8fe",
  mutedForeground: "#6b6f9a",
  accent: "#ebe9fd",
  accentForeground: "#5046e5",
  destructive: "#ef4444",
  destructiveForeground: "#ffffff",
  success: "#10b981",
  successLight: "#ecfdf5",
  successForeground: "#064e3b",
  warning: "#f59e0b",
  warningLight: "#fffbeb",
  warningForeground: "#78350f",
  border: "#ecedf8",
  borderStrong: "#d4d3f0",
  input: "#f3f3fb",
  ring: "#5046e5",
  overlay: "rgba(13, 15, 43, 0.5)",
  gradientPrimary: ["#5046e5", "#7c3aed"] as const,
  gradientHero: ["#4338ca", "#7c3aed"] as const,
  gradientCard: ["#5046e5", "#6d28d9"] as const,
  gradientSubtle: ["#f5f6ff", "#ebe9fd"] as const,
  gradientGold: ["#f59e0b", "#f97316"] as const,
  pro: "#7c3aed",
  proLight: "#f3e8ff",
};

export const Shadows = StyleSheet.create({
  xs: {
    shadowColor: "#5046e5",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  sm: {
    shadowColor: "#0d0f2b",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  md: {
    shadowColor: "#0d0f2b",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.09,
    shadowRadius: 14,
    elevation: 4,
  },
  lg: {
    shadowColor: "#5046e5",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 8,
  },
  glow: {
    shadowColor: "#7c3aed",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 7,
  },
  card: {
    shadowColor: "#5046e5",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 3,
  },
});

export const Typography = {
  h1: { fontSize: 26, fontWeight: "700" as const, color: Colors.foreground },
  h2: { fontSize: 20, fontWeight: "700" as const, color: Colors.foreground },
  h3: { fontSize: 16, fontWeight: "600" as const, color: Colors.foreground },
  body: { fontSize: 14, color: Colors.foreground, lineHeight: 21 },
  bodyMedium: { fontSize: 14, fontWeight: "500" as const, color: Colors.foreground },
  bodySemibold: { fontSize: 14, fontWeight: "600" as const, color: Colors.foreground },
  caption: { fontSize: 12, color: Colors.mutedForeground },
  captionMedium: { fontSize: 12, fontWeight: "500" as const, color: Colors.mutedForeground },
  tiny: { fontSize: 10, color: Colors.mutedForeground },
};
